name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t wtb-we-teman-budaya:latest .

      - name: Save Docker image to file
        run: docker save wtb-we-teman-budaya:latest -o wtb-we-teman-budaya.tar

      - name: Create .env file from secrets
        run: |
          cat <<EOF > .env
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          DEBUG=${{ secrets.DEBUG }}
          ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          DATABASE_USER=${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          DATABASE_PORT=${{ secrets.DATABASE_PORT }}
          EOF

      - name: Prepare deploy files
        run: |
          mkdir WTB--We-Teman-Budaya
          mv wtb-we-teman-budaya.tar .env docker-compose.yml WTB--We-Teman-Budaya/

      - name: Copy Docker image and .env to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "WTB--We-Teman-Budaya/*"
          target: "~/"

      - name: Deploy on remote server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/WTB--We-Teman-Budaya

            docker compose down || true
            docker rmi wtb-we-teman-budaya:latest || true
            
            docker load -i wtb-we-teman-budaya.tar
            rm wtb-we-teman-budaya.tar
            
            docker compose up -d